---
title: "Utah-Flowmap-Test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Test
```{r}
library(devtools)
#devtools::install_github("FlowmapBlue/flowmapblue.R")
library(flowmapblue)
library(tidyverse)
library(sf)
```

## Test

```{r}
locations <- tibble(
  id = c(1, 2, 3),
  name = c("New York", "London", "Rio de Janeiro"),
  lat = c(40.713543, 51.507425, -22.906241),
  lon = c(-74.011219, -0.127738, -43.180244)
)
```

```{r}
flows <- tibble(
  origin = c(1, 2, 3, 2, 1, 3),
  dest = c(2, 1, 1, 3, 3, 2),
  count = c(42, 51, 50, 40, 22, 42)
)
```

```{r}
mapboxAccessToken <- "pk.eyJ1IjoiY2RheTk3IiwiYSI6ImNscG4xYXUyYjBjaGgya3BqcXFyMnV5anYifQ.fuwqOztKXYj41tpGv-fI2Q"
flowmapblue(locations, flows, mapboxAccessToken, clustering = TRUE, darkMode = TRUE, animation = TRUE)
```

## Utah

```{r}
auto_pk_wide <- read_csv("data/fromTdm/v900_RTP_2050_peak_auto.csv")

# Convert wide format to long format
auto_pk_long <- auto_pk_wide %>%
  pivot_longer(cols = -auto, names_to = "dest", values_to = "count") %>%
  mutate(dest = as.numeric(dest)) %>%
  rename("origin" = "auto")

taz <- st_read("data/fromTdm/TAZ/TAZ.shp") %>%
  st_transform(4326) %>%
  st_centroid() %>%
  mutate(
    lon = st_coordinates(geometry)[, "X"],
    lat = st_coordinates(geometry)[, "Y"]
  ) %>%
  mutate(
    name = paste0(TAZID,"_",CITY_NAME)
  ) %>%
  rename("id" = "TAZID") %>%
  select(id,name,lat,lon) %>%
  as_tibble() %>%
  select(-geometry)
```

```{r}
map <- flowmapblue(taz, auto_pk_long, mapboxAccessToken, clustering = TRUE, darkMode = TRUE, animation = TRUE)
m
```


```{r}
htmlwidgets::saveWidget(map, "1-Utah-Peak-Auto-Flow.html", selfcontained = TRUE)
```


